# -*- coding: utf-8 -*-
"""cnn_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGLTDEzlGvIqpTTlfm8obEAUJrogwzrt
"""

import kagglehub
path = kagglehub.dataset_download("preetrank/indian-currency-real-vs-fake-notes-dataset")

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers, callbacks

# ──────────────────────────────────────────
# 1. PATHS & SETTINGS
# ──────────────────────────────────────────
DATA_PATH = "/root/.cache/kagglehub/datasets/preetrank/indian-currency-real-vs-fake-notes-dataset/versions/2"
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# ──────────────────────────────────────────
# 2. CHECK CLASS DISTRIBUTION FIRST
# ──────────────────────────────────────────
import os
for cls in os.listdir(DATA_PATH):
    cls_path = os.path.join(DATA_PATH, cls)
    if os.path.isdir(cls_path):
        print(f"{cls}: {len(os.listdir(cls_path))} images")

# ──────────────────────────────────────────
# 3. DATA AUGMENTATION TO PREVENT OVERFITTING
# ──────────────────────────────────────────
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomBrightness(0.1),
])

# ──────────────────────────────────────────
# 4. LOAD DATASET
# ──────────────────────────────────────────
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_PATH,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_PATH,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
print("Classes:", class_names)  # confirm which index is real vs fake

# ──────────────────────────────────────────
# 5. PERFORMANCE OPTIMIZATION
# ──────────────────────────────────────────
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds   = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# ──────────────────────────────────────────
# 6. USE TRANSFER LEARNING (MobileNetV2)
#    Much better than a small custom CNN
# ──────────────────────────────────────────
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False  # freeze pretrained layers first

inputs  = tf.keras.Input(shape=(224, 224, 3))
x       = data_augmentation(inputs)
x       = tf.keras.applications.mobilenet_v2.preprocess_input(x)
x       = base_model(x, training=False)
x       = layers.GlobalAveragePooling2D()(x)
x       = layers.Dropout(0.3)(x)
outputs = layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(inputs, outputs)

# ──────────────────────────────────────────
# 7. HANDLE CLASS IMBALANCE
# ──────────────────────────────────────────
# Count your classes and set weights accordingly
# Example: if fake=800, real=200 → real is underrepresented
# Adjust these numbers after checking your dataset above

total   = 1000   # replace with actual total
n_fake  = 800    # replace with actual fake count
n_real  = 200    # replace with actual real count

weight_fake = (1 / n_fake) * (total / 2)
weight_real = (1 / n_real) * (total / 2)

# class_names prints alphabetically — check which index is which
# e.g. if class_names = ['fake', 'real'] → {0: weight_fake, 1: weight_real}
class_weight = {0: weight_fake, 1: weight_real}
print("Class weights:", class_weight)

# ──────────────────────────────────────────
# 8. COMPILE WITH CALLBACKS
# ──────────────────────────────────────────
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy',
             tf.keras.metrics.Precision(name='precision'),
             tf.keras.metrics.Recall(name='recall')]
)

early_stop = callbacks.EarlyStopping(
    monitor='val_loss', patience=5, restore_best_weights=True
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor='val_loss', factor=0.3, patience=3
)

# ──────────────────────────────────────────
# 9. TRAIN — PHASE 1 (frozen base)
# ──────────────────────────────────────────
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    class_weight=class_weight,
    callbacks=[early_stop, reduce_lr]
)

# ──────────────────────────────────────────
# 10. FINE TUNING — PHASE 2 (unfreeze top layers)
# ──────────────────────────────────────────
base_model.trainable = True
fine_tune_at = 100  # unfreeze only last layers

for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),  # very low LR
    loss='binary_crossentropy',
    metrics=['accuracy',
             tf.keras.metrics.Precision(name='precision'),
             tf.keras.metrics.Recall(name='recall')]
)

history_fine = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weight,
    callbacks=[early_stop, reduce_lr]
)

# ──────────────────────────────────────────
# 11. PLOT RESULTS
# ──────────────────────────────────────────
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'],     label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy'); plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'],     label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss'); plt.legend()

plt.tight_layout()
plt.show()

import tensorflow as tf

# ──────────────────────────────────────────
# 12. SAVE MODEL
# ──────────────────────────────────────────
model.export("currency_detector.tflite")

