# -*- coding: utf-8 -*-
"""project of cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BC1Smpg0yx6L_-7-5_ATYTkMgOvQU7Y-
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("preetrank/indian-currency-real-vs-fake-notes-dataset")

print("Path to dataset files:", path)

import os

DATA_PATH = "/root/.cache/kagglehub/datasets/preetrank/indian-currency-real-vs-fake-notes-dataset/versions/2"

os.listdir(DATA_PATH)

os.listdir(DATA_PATH + "/data")

import os

DATA_PATH = "/root/.cache/kagglehub/datasets/preetrank/indian-currency-real-vs-fake-notes-dataset/versions/2"

os.listdir(DATA_PATH)

import tensorflow as tf

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_PATH,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_PATH,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
print("Classes:", class_names)

model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255, input_shape=(224, 224, 3)),

    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(64, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(128, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

model.save('my_model.keras')

print(class_names)

